# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core
BLOCKSDSEXT	?= /opt/blocksds/external

# Libraries

LIBS		:= -lnds7 -ldswifi7 -lmikmod7 -lc
LIBDIRS		:= $(BLOCKSDS)/libs/libnds \
		   $(BLOCKSDS)/libs/dswifi \
		   $(BLOCKSDSEXT)/libmikmod

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm7
