# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= libmikmod_nitrofs

GAME_TITLE	:= Songs NitroFS
GAME_SUBTITLE	:= libmikmod

NITROFSDIR	 := nitrofs

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
