# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# Source code paths

BINDIRS		:= arm9/data

# Libraries

LIBS		:= -lnds9 -lmikmod9 -lc
LIBDIRS		:= $(BLOCKSDS)/libs/libmikmod \
		   $(BLOCKSDS)/libs/libnds

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm9

