# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= libmikmod_embedded

GAME_TITLE	:= Songs embedded
GAME_SUBTITLE	:= libmikmod

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
